### ISSUE TITLE
Crash http://www.wowhead.com/spell=61999/raise-ally

### ISSUE THREAD

**Issue by Re3os** [healthstone/RE#8]
Last rev.
http://pastebin.com/aL0skAfT

**Comment by kvipka** [comment]
Are you sure, that you using RE, and RE last rev?
1st part: https://github.com/healthstone/RE/commit/7c66e704e5ee6539fa12f1cda2d22a04e55bbf5b
2nd part: https://github.com/healthstone/RE/commit/5f5e5325432980a9dc32dc69e2a873dfdb693007

**Comment by Re3os** [comment]
Yes

**Comment by kvipka** [comment]
can you explain. Who exactly must leave/logout and etc for crash?

**Comment by Re3os** [comment]
I'm revert http://www.wowhead.com/spell=61999/raise-ally,no crash.
